lib/novel_service_web/router.ex
defmodule NovelServiceWeb.Router do
  use NovelServiceWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {NovelServiceWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :auth do
    plug NovelService.Accounts.Pipeline
    plug NovelService.Accounts.CurrentUser
  end

  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated
  end

  scope "/", NovelServiceWeb do
    pipe_through [:browser, :auth]

    get "/", ArticleController, :home
    get "/signin", UserController, :new
    post "/signin", UserController, :create
    get "/login", SessionController, :new
    post "/login", SessionController, :login
    delete "/logout", SessionController, :logout
    get "/novels", ArticleController, :index
    get "/novels/rank", ArticleController, :rank
    get "/novels/:id", ArticleController, :show
    get "/userlists", UserController, :index
    #    get "/userlists/:id", UserController, :show
    get "/novels/summary/:id", ArticleController, :summary
    get "/userlists/userinfo/:id", UserController, :userinfo
  end

  scope "/", NovelServiceWeb do
    pipe_through [:browser, :auth, :ensure_auth]
    resources "/users", UserController, except: [:new, :create, :index, :show]
    resources "/articles", ArticleController, except: [:index, :show]
    get "/mypage/:id", UserController, :mypage
    get "/mypage/myinfo/:id", UserController, :myinfo
    get "/mynovellists/", ArticleController, :mynovellists
    get "/users/:id/editpass", UserController, :editpass
  end

  # Other scopes may use custom stacks.
  # scope "/api", NovelServiceWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: NovelServiceWeb.Telemetry
    end
  end
end

lib/novel_service_web/views/layout_view.ex
defmodule NovelServiceWeb.LayoutView do
  use NovelServiceWeb, :view

  alias NovelService.Accounts.Guardian

  def current_user(conn) do
    Guardian.Plug.current_resource(conn)
  end
end

lib/novel_service_web/templates/layout/app.html.eex
<main role="main" class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/novel_service_web/templates/layout/live.html.leex
<main role="main" class="container">
  <p class="alert alert-info" role="alert" phx-click="lv:clear-flash" phx-value-key="info">
    <%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert" phx-click="lv:clear-flash" phx-value-key="error">
    <%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/novel_service_web/templates/layout/root.html.leex
<!doctype html>
<html lang="ja">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <%= csrf_meta_tag() %>
  <%= live_title_tag assigns[:page_title] || "NovelService", suffix: " · Phoenix Framework" %>
  <link phx-track-static rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>" />
  <script defer phx-track-static type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <%= link to: Routes.article_path(@conn, :home), class: "navbar-brand" do %>
    <img src="<%= Routes.static_path(@conn, "/images/branchN.png") %>" widith="30" height="30"
      alt="Phoenix Framework Logo" />
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerRight"
      aria-controls="navbarTogglerRight" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerRight">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item">
          <%= link to: Routes.article_path(@conn, :home), class: "nav-link" do %>
          ホーム<span class="sr-only">(current)</span>
          <% end %>
        </li>
        <%= if @current_user do %>
        <li class="nav-item">
          <%= link to: Routes.user_path(@conn, :mypage, current_user(@conn)), class: "nav-link" do %>
          マイページ
          <% end %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link to: Routes.session_path(@conn, :new), class: "nav-link" do %>
          マイページ
          <% end %>
        </li>
        <% end %>
        <li class="nav-item">
          <%= link to: Routes.article_path(@conn, :index), class: "nav-link" do %>
          小説検索
          <% end %>
        </li>
        <li class="nav-item">
          <%= link to: Routes.user_path(@conn, :index), class: "nav-link" do %>
          ユーザー検索
          <% end %>
        </li>
        <li class="nav-item">
          <%= link to: Routes.article_path(@conn, :rank), class: "nav-link" do %>
          ランキング
          <% end %>
        </li>
      </ul>
      <form class="form-inline">
        <%= form_for @conn, Routes.article_path(@conn, :index), [method: :get], fn f -> %>
        <%= search_input f, :query, class: "form-control", type: "search", placeholder: "小説検索" %>
        <%= submit "検索", class: "btn btn-outline-success" %>
        <% end %>
      </form>
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <%= if @current_user do %>
        <li class="nav-item">
          <%= link "ログアウト", to: Routes.session_path(@conn, :logout), method: :delete, class: "nav-link" %></li>
        <% else %>
        <li class="nav-item"><%= link "ログイン", to: Routes.session_path(@conn, :new), class: "nav-link" %></li>
        <% end %>
        <%= unless current_user(@conn) do %>
        <li class="nav-item">
          <%= link to: Routes.user_path(@conn, :new), class: "nav-link" do %>
          ユーザー登録
          <% end %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link to: Routes.user_path(@conn, :mypage, current_user(@conn)), class: "nav-link" do %>
          マイページ
          <% end %>
        </li>
        <% end %>
      </ul>
    </div>
  </nav>
  <%= @inner_content %>
  <footer class="footer mt-auto py-3">
    <div class="container">
      <span class="text-muted">フッターのコンテンツをここに置きます．</span>
    </div>
  </footer>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
  </script>
  <script>
    $(document).on('click', function () {
      $('.navbar-collapse').collapse('hide');
    })
  </script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
    integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous">
  </script>

</body>

</html>